import type { Metadata } from 'next';
import Link from 'next/link';
import {
  BarChart3,
  CalendarClock,
  FileText,
  Images,
  Languages,
  Layers,
  PenLine,
  Search,
  ShieldCheck,
  Users,
  Wand2,
  Workflow,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { FeatureCard, Section, SectionHeading } from '@/components/marketing/sections';
import { PLATFORMS, PLATFORM_META } from '@/lib/platforms';

export const metadata: Metadata = {
  title: 'Features',
  description: 'Everything MarketPilot AI does, and the limits we are honest about.',
};

export default function FeaturesPage() {
  return (
    <>
      <Section>
        <SectionHeading
          eyebrow="Features"
          title="Built to produce work you would actually publish"
          description="Not a prompt box with a logo on it. Each part exists because a campaign needs it."
        />

        <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          <FeatureCard icon={<Wand2 className="size-5" />} title="Product understanding">
            Vision analysis reads your photo for category, packaging and use-case clues, and marks what it could not
            determine instead of inventing it.
          </FeatureCard>
          <FeatureCard icon={<PenLine className="size-5" />} title="Native copy per network">
            Seven platforms, seven separate generations from one strategy. No single caption pasted everywhere.
          </FeatureCard>
          <FeatureCard icon={<Workflow className="size-5" />} title="Strategy before copy">
            The angle, key message and proof points are decided first, so every piece says the same thing in its own
            voice.
          </FeatureCard>
          <FeatureCard icon={<Images className="size-5" />} title="Creative that keeps your product">
            Images are composed from your actual photograph — background, framing and overlay are generated, the product
            is not touched.
          </FeatureCard>
          <FeatureCard icon={<Search className="size-5" />} title="SEO package">
            Title, meta description, keywords, search intent and FAQ suggestions for the page behind the campaign.
          </FeatureCard>
          <FeatureCard icon={<ShieldCheck className="size-5" />} title="Quality control">
            Unsupported claims, fabricated proof, hashtag problems and format violations are flagged before you read the
            content — blockers stop approval entirely.
          </FeatureCard>
          <FeatureCard icon={<CalendarClock className="size-5" />} title="Server-side scheduling">
            Queue a week across networks in your own timezone. Nothing depends on a browser tab staying open.
          </FeatureCard>
          <FeatureCard icon={<BarChart3 className="size-5" />} title="Real analytics only">
            Metrics come from each platform&rsquo;s API. Anything a platform will not give us is shown as unavailable, never
            filled in with an estimate.
          </FeatureCard>
          <FeatureCard icon={<FileText className="size-5" />} title="Content library">
            Search every piece ever generated by brand, platform, status or text, and repurpose any of it.
          </FeatureCard>
          <FeatureCard icon={<Layers className="size-5" />} title="Versioning">
            Every generation is snapshotted. Restore an earlier version at any time — restoring is itself undoable.
          </FeatureCard>
          <FeatureCard icon={<Users className="size-5" />} title="Roles enforced server-side">
            Owner, admin, editor and viewer. Permissions are checked on the server, not hidden in the interface.
          </FeatureCard>
          <FeatureCard icon={<Languages className="size-5" />} title="Multi-market">
            Content language, market and timezone are per brand, so one workspace can run campaigns in several
            countries.
          </FeatureCard>
        </div>
      </Section>

      <Section tone="muted">
        <SectionHeading
          eyebrow="Platform support"
          title="What each network's API actually allows"
          description="These limits are the platforms', not ours. We show them up front so nothing surprises you at publish time."
        />

        <div className="mt-10 overflow-x-auto scroll-panel">
          <table className="w-full min-w-[40rem] border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-ink-200">
                <th scope="col" className="py-2.5 pr-4 font-semibold text-ink-900">
                  Platform
                </th>
                <th scope="col" className="py-2.5 pr-4 font-semibold text-ink-900">
                  Can publish
                </th>
                <th scope="col" className="py-2.5 font-semibold text-ink-900">
                  The catch
                </th>
              </tr>
            </thead>
            <tbody>
              {PLATFORMS.map((platform) => {
                const meta = PLATFORM_META[platform];
                return (
                  <tr key={platform} className="border-b border-ink-100 align-top">
                    <th scope="row" className="py-3 pr-4 font-medium text-ink-900">
                      <span className="flex items-center gap-2">
                        <span className="size-2.5 rounded-full" style={{ backgroundColor: meta.color }} aria-hidden="true" />
                        {meta.label}
                      </span>
                    </th>
                    <td className="py-3 pr-4 text-ink-600">{meta.capabilities.join(', ')}</td>
                    <td className="py-3 text-ink-600">{meta.limitations[0]}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        <p className="mt-6 max-w-2xl text-sm text-ink-600">
          Where an API cannot accept a post for your account, the campaign is marked as needing a manual publish and you
          get the media and copy in one click. We never show a post as published when it is not.
        </p>
      </Section>

      <Section>
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-ink-900">Start with one product</h2>
          <Button asChild size="lg" className="mt-6">
            <Link href="/signup">Create your first campaign</Link>
          </Button>
        </div>
      </Section>
    </>
  );
}
