import path from 'node:path';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { env, usingEmbeddedDatabase } from '@/lib/env';
import { logger } from '@/lib/logger';
import * as schema from './schema';

export type Database = NodePgDatabase<typeof schema>;

export { schema };

const MIGRATIONS_FOLDER = path.join(process.cwd(), 'drizzle');

type Handle = { db: Database; dispose: () => Promise<void>; runMigrator: () => Promise<void> };

/**
 * Two drivers, one schema and one set of SQL migrations:
 *
 *   - development (no DATABASE_URL): PGlite, a real PostgreSQL build compiled to
 *     WASM, persisted under ./.pglite. Zero setup, same dialect as production.
 *   - production (DATABASE_URL set): node-postgres against managed PostgreSQL.
 *
 * Because both speak PostgreSQL, migrations generated by drizzle-kit apply
 * unchanged in either mode.
 */
async function createHandle(): Promise<Handle> {
  if (usingEmbeddedDatabase()) {
    const { PGlite } = await import('@electric-sql/pglite');
    const { drizzle } = await import('drizzle-orm/pglite');
    const { migrate } = await import('drizzle-orm/pglite/migrator');

    // PGLITE_DIR lets tests point at a throwaway directory.
    const client = new PGlite(process.env['PGLITE_DIR'] ?? path.join(process.cwd(), '.pglite'));
    const db = drizzle(client, { schema, logger: false }) as unknown as Database;

    const runMigrator = () => migrate(db as never, { migrationsFolder: MIGRATIONS_FOLDER });

    await runMigrator();
    logger.info('db.ready', { driver: 'pglite' });

    return { db, dispose: () => client.close(), runMigrator };
  }

  const { Pool } = await import('pg');
  const { drizzle } = await import('drizzle-orm/node-postgres');
  const { migrate } = await import('drizzle-orm/node-postgres/migrator');

  const pool = new Pool({
    connectionString: env().DATABASE_URL,
    max: 10,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 10_000,
  });
  const db = drizzle(pool, { schema, logger: false });

  const runMigrator = () => migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });

  // Outside production the schema is brought up to date on first use, which is
  // what makes `npm run dev` work from a clean checkout. In production the
  // schema is changed by `npm run db:migrate` as an explicit deploy step, so a
  // cold-starting web instance never races another one over the same DDL.
  if (env().NODE_ENV !== 'production') {
    await runMigrator();
  }
  logger.info('db.ready', { driver: 'node-postgres' });

  return { db, dispose: () => pool.end(), runMigrator };
}

// Cached on globalThis so Next.js hot reloads reuse one connection/instance.
const globalRef = globalThis as typeof globalThis & { __marketpilotDb?: Promise<Handle> };

function handle(): Promise<Handle> {
  globalRef.__marketpilotDb ??= createHandle();
  return globalRef.__marketpilotDb;
}

/** Resolves the shared database instance, applying migrations on first use. */
export async function getDb(): Promise<Database> {
  const { db } = await handle();
  // Started here rather than from instrumentation.ts: this module is only ever
  // loaded in the Node runtime, so the driver imports never reach an edge
  // bundle. See startInlineWorkerOnce for why the dev worker is in-process.
  if (!workerStarted) {
    workerStarted = true;
    const { startInlineWorkerOnce } = await import('@/server/jobs/inline');
    startInlineWorkerOnce();
  }
  return db;
}

let workerStarted = false;

/**
 * Applies every pending migration, whatever NODE_ENV says.
 *
 * This is the production path: `getDb()` deliberately does not migrate there,
 * so the deploy step has to ask for it explicitly.
 */
export async function runMigrations(): Promise<void> {
  const { runMigrator } = await handle();
  await runMigrator();
}

/** Closes the pool / embedded instance. Used by tests and worker shutdown. */
export async function closeDb(): Promise<void> {
  const existing = globalRef.__marketpilotDb;
  if (!existing) return;
  globalRef.__marketpilotDb = undefined;
  await (await existing).dispose();
}
