import 'server-only';
import { and, desc, eq, gte, ilike, inArray, isNull, lte, or, sql } from 'drizzle-orm';
import type { Platform } from '@/lib/platforms';
import { getDb } from '@/server/db';
import { brands, campaigns, content, products } from '@/server/db/schema';
import type { AuthContext } from '@/server/auth/context';

export type ContentFilters = {
  brandId?: string;
  productId?: string;
  campaignId?: string;
  platform?: Platform;
  format?: string;
  status?: string;
  search?: string;
  from?: Date;
  to?: Date;
  limit?: number;
  offset?: number;
};

export type ContentLibraryRow = {
  id: string;
  campaignId: string;
  campaignTitle: string;
  brandName: string;
  productName: string | null;
  platform: Platform;
  format: string;
  status: string;
  hashtags: string[];
  qualityFlagCount: number;
  preview: string;
  updatedAt: Date;
};

/** First readable line of a piece, used as the list preview. */
function previewOf(fields: Record<string, unknown>): string {
  for (const key of ['hook', 'caption', 'primaryText', 'post', 'title', 'pinTitle', 'description']) {
    const value = fields[key];
    if (typeof value === 'string' && value.trim()) return value.trim().slice(0, 220);
  }
  return '';
}

/**
 * Cross-campaign search over every generated piece.
 *
 * All filtering happens in SQL and is always scoped to the caller's
 * organization, so the library can never surface another tenant's content.
 */
export async function searchContent(ctx: AuthContext, filters: ContentFilters): Promise<ContentLibraryRow[]> {
  const db = await getDb();

  const where = [eq(content.organizationId, ctx.organization.id), isNull(content.deletedAt)];

  if (filters.campaignId) where.push(eq(content.campaignId, filters.campaignId));
  if (filters.platform) where.push(eq(content.platform, filters.platform));
  if (filters.format) where.push(eq(content.format, filters.format as never));
  if (filters.status) where.push(eq(content.status, filters.status as never));
  if (filters.brandId) where.push(eq(campaigns.brandId, filters.brandId));
  if (filters.productId) where.push(eq(campaigns.productId, filters.productId));
  if (filters.from) where.push(gte(content.updatedAt, filters.from));
  if (filters.to) where.push(lte(content.updatedAt, filters.to));

  if (filters.search) {
    const term = `%${filters.search}%`;
    // Matches the campaign title or any text inside the generated fields.
    where.push(or(ilike(campaigns.title, term), sql`${content.fields}::text ilike ${term}`)!);
  }

  const rows = await db
    .select({
      id: content.id,
      campaignId: content.campaignId,
      campaignTitle: campaigns.title,
      brandName: brands.name,
      productName: products.name,
      platform: content.platform,
      format: content.format,
      status: content.status,
      hashtags: content.hashtags,
      qualityFlags: content.qualityFlags,
      fields: content.fields,
      updatedAt: content.updatedAt,
    })
    .from(content)
    .innerJoin(campaigns, eq(campaigns.id, content.campaignId))
    .innerJoin(brands, eq(brands.id, campaigns.brandId))
    .leftJoin(products, eq(products.id, campaigns.productId))
    .where(and(...where))
    .orderBy(desc(content.updatedAt))
    .limit(filters.limit ?? 50)
    .offset(filters.offset ?? 0);

  return rows.map((row) => ({
    id: row.id,
    campaignId: row.campaignId,
    campaignTitle: row.campaignTitle,
    brandName: row.brandName,
    productName: row.productName,
    platform: row.platform,
    format: row.format,
    status: row.status,
    hashtags: row.hashtags,
    qualityFlagCount: row.qualityFlags.length,
    preview: previewOf(row.fields),
    updatedAt: row.updatedAt,
  }));
}

/**
 * Repurposing: copies an existing piece's substance into a new campaign aimed
 * at different platforms. The new campaign starts in draft and is generated by
 * the normal pipeline, so the copy is written natively for each target rather
 * than pasted across.
 */
export async function contentForRepurpose(
  ctx: AuthContext,
  contentId: string,
): Promise<{ campaignId: string; brandId: string; productId: string | null; platform: Platform } | null> {
  const db = await getDb();

  const [row] = await db
    .select({
      campaignId: content.campaignId,
      brandId: campaigns.brandId,
      productId: campaigns.productId,
      platform: content.platform,
    })
    .from(content)
    .innerJoin(campaigns, eq(campaigns.id, content.campaignId))
    .where(and(eq(content.id, contentId), eq(content.organizationId, ctx.organization.id)))
    .limit(1);

  return row ?? null;
}

export async function contentCountsByStatus(ctx: AuthContext): Promise<Record<string, number>> {
  const db = await getDb();
  const rows = await db
    .select({ status: content.status, value: sql<number>`count(*)` })
    .from(content)
    .where(and(eq(content.organizationId, ctx.organization.id), isNull(content.deletedAt)))
    .groupBy(content.status);

  return Object.fromEntries(rows.map((row) => [row.status, Number(row.value)]));
}

/** Bulk status change used by the library's selection actions. */
export async function bulkUpdateContentStatus(
  ctx: AuthContext,
  contentIds: string[],
  status: 'draft' | 'approved',
): Promise<number> {
  if (contentIds.length === 0) return 0;
  const db = await getDb();

  const updated = await db
    .update(content)
    .set({ status, updatedAt: new Date() })
    .where(and(inArray(content.id, contentIds), eq(content.organizationId, ctx.organization.id)))
    .returning({ id: content.id });

  return updated.length;
}
